# fly.toml app configuration file generated for tvbot-prod on 2024-10-22T22:55:56-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tvbot-prod'
primary_region = 'ord'

[build]

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  TZ = "America/Chicago"
  REGISTER_COMMANDS = "true"
