name: Fly Deploy
on:
  workflow_dispatch:
  workflow_call:
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: tvbot-prod
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --image ghcr.io/cbackas/tvbot:latest
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
