name: Fly Deploy
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        type: string
        required: false
        default: 'latest'
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --image ghcr.io/cbackas/tvbot:${{ inputs.version }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
