name: Pull Request
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
jobs:
  pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: deepakputhraya/action-pr-title@master
        with:
          allowed_prefixes: 'Breaking:,Fix:,Update:,New:,Build:,Upgrade:,Chore:,NoBuild:'
          prefix_case_sensitive: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: deno lint
  test-semantic-release:
    uses: ./.github/workflows/semantic-release.yml
    with:
      dry_run: true
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          tags: cbackas/tvbot:pr
