name: Push
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*.*.*'
jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/')
    concurrency: push-concurrency
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: denoland/setup-deno@v2
      - name: Install Semantic Release
        run: deno install npm:semantic-release@^24.1.2 npm:@codedependant/semantic-release-docker@^5.0.3 npm:conventional-changelog-eslint@^6.0.0
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Semantic Release
        run: deno run -A npm:semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          DOCKER_REGISTRY_USER: ${{ github.actor }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  notify:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    concurrency: push-concurrency
    steps:
      - uses: actions/checkout@v4
      - name: Extract tag name
        id: tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: "flyctl deploy --image ghcr.io/cbackas/tvbot:${{ env.TAG_NAME }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: 'Version {{ TAG_NAME }} of {{ EVENT_PAYLOAD.repository.full_name }} has been released and deployed'
